name: book_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  webdriver: ^3.0.0  
  test: ^1.24.0
  
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  collection: ^1.19.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  carousel_slider: ^5.0.0
  intl: ^0.20.2
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/dacnhantam.jpg
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/5.jpg
    - assets/images/6.jpg
    - assets/images/

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif-VariableFont_wdth,wght.ttf
