// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZm52EKhW7Sqw9JFswTwEyU9zyGGZ2Kv0',
    appId: '1:259381247920:web:7d260750c7147d5ac46075',
    messagingSenderId: '259381247920',
    projectId: 'bookstore-f41cb',
    authDomain: 'bookstore-f41cb.firebaseapp.com',
    storageBucket: 'bookstore-f41cb.firebasestorage.app',
    measurementId: 'G-3MT3H4RF4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT0lDHKj1UShBaolfwFB1XUt-Tr-qNfpE',
    appId: '1:259381247920:android:83816ef0389d5da0c46075',
    messagingSenderId: '259381247920',
    projectId: 'bookstore-f41cb',
    storageBucket: 'bookstore-f41cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3oJwOrIQsl_KonFbtxvfl9h2c0_LEEtw',
    appId: '1:259381247920:ios:22cc8cbaa901cd97c46075',
    messagingSenderId: '259381247920',
    projectId: 'bookstore-f41cb',
    storageBucket: 'bookstore-f41cb.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3oJwOrIQsl_KonFbtxvfl9h2c0_LEEtw',
    appId: '1:259381247920:ios:22cc8cbaa901cd97c46075',
    messagingSenderId: '259381247920',
    projectId: 'bookstore-f41cb',
    storageBucket: 'bookstore-f41cb.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZm52EKhW7Sqw9JFswTwEyU9zyGGZ2Kv0',
    appId: '1:259381247920:web:458d4797f820fb61c46075',
    messagingSenderId: '259381247920',
    projectId: 'bookstore-f41cb',
    authDomain: 'bookstore-f41cb.firebaseapp.com',
    storageBucket: 'bookstore-f41cb.firebasestorage.app',
    measurementId: 'G-SHRKVVMQKE',
  );
}
